@extends('layouts.admin')
@section('title','รายงาน | PrintShop') @section('page-title','รายงานภาพรวมร้าน') @section('page-subtitle','สรุปจำนวนงาน สถานะการทำงาน การชำระเงิน และรายรับ')
@section('content')
<section class="stats"><div class="stat" style="--accent:#2563eb"><div class="stat-label">งานทั้งหมด</div><div class="stat-value">{{ $totalOrders }}</div></div><div class="stat" style="--accent:#f57b20"><div class="stat-label">รอตรวจไฟล์</div><div class="stat-value">{{ $pendingOrders }}</div></div><div class="stat" style="--accent:#7c5ac7"><div class="stat-label">รอชำระเงิน</div><div class="stat-value">{{ $waitingPaymentOrders }}</div></div><div class="stat" style="--accent:#11a8c3"><div class="stat-label">กำลังดำเนินการ</div><div class="stat-value">{{ $processingOrders }}</div></div><div class="stat" style="--accent:#18a05e"><div class="stat-label">พร้อมรับ</div><div class="stat-value">{{ $readyOrders }}</div></div><div class="stat" style="--accent:#2563eb"><div class="stat-label">เสร็จสิ้น</div><div class="stat-value">{{ $completedOrders }}</div></div><div class="stat" style="--accent:#df4444"><div class="stat-label">ยกเลิก</div><div class="stat-value">{{ $cancelledOrders }}</div></div><div class="stat" style="--accent:#18a05e"><div class="stat-label">ชำระแล้ว</div><div class="stat-value">{{ $paidOrders }}</div></div></section>
<div class="revenue-card" style="margin-bottom:20px"><small>รายรับรวมจากงานที่ชำระแล้ว</small><strong>{{ number_format($totalRevenue,2) }}</strong><span>บาท</span></div>
<div class="table-card"><div class="table-top"><h2>รายการงานทั้งหมด</h2><span>เรียงจากงานล่าสุด</span></div><div class="table-scroll"><table><thead><tr><th>เลขคิว</th><th>เลขที่งาน</th><th>ลูกค้า</th><th>บริการ</th><th>ราคา</th><th>สถานะงาน</th><th>การชำระเงิน</th><th>วันที่</th></tr></thead><tbody>
@forelse($orders as $order) @php $text=match($order->status){'pending'=>'รอตรวจไฟล์','waiting_payment'=>'รอชำระเงิน','processing'=>'กำลังดำเนินการ','ready'=>'พร้อมรับ','completed'=>'เสร็จสิ้น','cancelled'=>'ยกเลิก',default=>$order->status}; $cls=match($order->status){'pending'=>'b-pending','waiting_payment'=>'b-waiting','processing'=>'b-processing','ready'=>'b-ready','completed'=>'b-completed','cancelled'=>'b-cancelled',default=>'b-pending'}; @endphp
<tr><td class="queue">{{ $order->queue_no ?? '-' }}</td><td>{{ $order->order_no }}</td><td>{{ $order->user?->name ?? '-' }}</td><td>{{ $order->items->first()?->service?->name ?? '-' }}</td><td class="money">{{ number_format($order->total_price,2) }} บาท</td><td><span class="badge {{ $cls }}">{{ $text }}</span></td><td>@if($order->payment_status==='paid')<span class="badge b-paid">ชำระแล้ว</span>@else<span class="badge b-unpaid">ยังไม่ชำระ</span>@endif</td><td>{{ $order->created_at->format('d/m/Y H:i') }}</td></tr>
@empty<tr><td colspan="8" class="empty">ยังไม่มีรายการงาน</td></tr>@endforelse
</tbody></table></div></div>
@endsection