@extends('layouts.staff')
@section('title','คิวงานหน้าร้าน | PrintShop') @section('page-title','คิวงานหน้าร้าน') @section('page-subtitle','ตรวจงาน เปิดไฟล์ ตรวจการชำระเงิน สั่งพิมพ์ และอัปเดตสถานะจากหน้าจอเดียว')
@section('content')
<section class="stats"><div class="stat" style="--accent:#2563eb"><div class="stat-label">งานทั้งหมด</div><div class="stat-value">{{ $totalOrders }}</div></div><div class="stat" style="--accent:#f57b20"><div class="stat-label">รอตรวจไฟล์</div><div class="stat-value">{{ $pendingOrders }}</div></div><div class="stat" style="--accent:#7c5ac7"><div class="stat-label">รอชำระเงิน</div><div class="stat-value">{{ $waitingPaymentOrders }}</div></div><div class="stat" style="--accent:#11a8c3"><div class="stat-label">กำลังดำเนินการ</div><div class="stat-value">{{ $processingOrders }}</div></div><div class="stat" style="--accent:#18a05e"><div class="stat-label">พร้อมรับ</div><div class="stat-value">{{ $readyOrders }}</div></div></section>
<div class="table-card"><div class="table-top"><div><h2>รายการคิวงาน</h2><span>เลือกดูตามสถานะได้</span></div><div class="filterbar"><button class="filter-btn active" data-filter="all">ทั้งหมด</button><button class="filter-btn" data-filter="pending">รอตรวจไฟล์</button><button class="filter-btn" data-filter="waiting_payment">รอชำระเงิน</button><button class="filter-btn" data-filter="processing">กำลังพิมพ์</button><button class="filter-btn" data-filter="ready">พร้อมรับ</button></div></div><div class="table-scroll"><table><thead><tr><th>เลขคิว</th><th>ลูกค้า</th><th>บริการ</th><th>ราคา</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody id="orders">
@forelse($orders as $order) @php $item=$order->items->first(); $text=match($order->status){'pending'=>'รอตรวจไฟล์','waiting_payment'=>'รอชำระเงิน','processing'=>'กำลังดำเนินการ','ready'=>'พร้อมรับ','completed'=>'เสร็จสิ้น','cancelled'=>'ยกเลิก',default=>$order->status}; $cls=match($order->status){'pending'=>'b-pending','waiting_payment'=>'b-waiting','processing'=>'b-processing','ready'=>'b-ready','completed'=>'b-completed','cancelled'=>'b-cancelled',default=>'b-pending'}; @endphp
<tr data-status="{{ $order->status }}"><td><div class="queue">{{ $order->queue_no ?? '-' }}</div><small>{{ $order->order_no }}</small></td><td><strong>{{ $order->user?->name ?? '-' }}</strong><br><small>{{ $order->user?->email ?? '-' }}</small></td><td><strong>{{ $item?->service?->name ?? '-' }}</strong><br><small>{{ $item?->paper_size ?? '-' }} • {{ $item?->quantity ?? 1 }} ชุด</small></td><td class="money">{{ number_format($order->total_price,2) }} ฿</td><td><span class="badge {{ $cls }}">{{ $text }}</span></td><td><div class="actions"><a class="btn btn-orange" href="{{ route('staff.orders.show',$order) }}">รายละเอียด</a><a class="btn btn-green" href="{{ route('staff.orders.print',$order) }}">🖨️ สั่งพิมพ์</a></div></td></tr>
@empty<tr><td colspan="6" class="empty">ยังไม่มีงานในระบบ</td></tr>@endforelse
</tbody></table></div></div>
<section id="workflow" class="panel" style="margin-top:20px"><div class="section-head" style="margin-top:0"><div><h2>ขั้นตอนการทำงาน</h2><p>คู่มือย่อสำหรับพนักงาน</p></div></div><div class="stats"><div class="stat" style="--accent:#f57b20"><div class="stat-label">1. ตรวจรายละเอียด</div><div style="margin-top:8px;color:#6d8093">ตรวจไฟล์และคำสั่งงาน</div></div><div class="stat" style="--accent:#7c5ac7"><div class="stat-label">2. ตรวจชำระเงิน</div><div style="margin-top:8px;color:#6d8093">ตรวจสลิปและยืนยันผล</div></div><div class="stat" style="--accent:#11a8c3"><div class="stat-label">3. สั่งพิมพ์</div><div style="margin-top:8px;color:#6d8093">เปิดไฟล์และดำเนินงาน</div></div><div class="stat" style="--accent:#18a05e"><div class="stat-label">4. พร้อมรับ</div><div style="margin-top:8px;color:#6d8093">อัปเดตเพื่อแจ้งลูกค้า</div></div></div></section>
@endsection
@push('scripts')<script>document.querySelectorAll('.filter-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;document.querySelectorAll('#orders tr[data-status]').forEach(r=>r.style.display=(f==='all'||r.dataset.status===f)?'':'none')}));</script>@endpush